server:
  port: 8082
  servlet:
    context-path: /info

spring:
  datasource:
    url: ${DBMS_CONNECTION:}
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: ${DBMS_USERNAME:}
    password: ${DBMS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: ${DBKK_CONNECTION:}:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      client:
        config:
            default:
              connect-timeout: 60000
              read-timeout: 120000
            file-service:
                url: ${FEIGN_FILE:}
                connect-timeout: 30000
                read-timeout: 60000
            auth-service:
                url: ${FEIGN_AUTH:}
                connect-timeout: 30000
                read-timeout: 60000
            product-service:
                url: ${FEIGN_PRODUCT:}
                connect-timeout: 30000
                read-timeout: 60000
jwt:
  signerKey: ${JWT_SIGNERKEY:}


logging:
  level:
    iuh.fit.se.service.impl: DEBUG
    iuh.fit.se.repository.httpclient: DEBUG  # Log Feign clients
    feign: DEBUG  # Enable Feign logging
    org.springframework.web: INFO
    org.springframework.cloud.openfeign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"